require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DistrictEffectsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # DistrictEffect. As you add validations to DistrictEffect, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DistrictEffectsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all district_effects as @district_effects" do
      district_effect = DistrictEffect.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:district_effects)).to eq([district_effect])
    end
  end

  describe "GET show" do
    it "assigns the requested district_effect as @district_effect" do
      district_effect = DistrictEffect.create! valid_attributes
      get :show, {:id => district_effect.to_param}, valid_session
      expect(assigns(:district_effect)).to eq(district_effect)
    end
  end

  describe "GET new" do
    it "assigns a new district_effect as @district_effect" do
      get :new, {}, valid_session
      expect(assigns(:district_effect)).to be_a_new(DistrictEffect)
    end
  end

  describe "GET edit" do
    it "assigns the requested district_effect as @district_effect" do
      district_effect = DistrictEffect.create! valid_attributes
      get :edit, {:id => district_effect.to_param}, valid_session
      expect(assigns(:district_effect)).to eq(district_effect)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DistrictEffect" do
        expect {
          post :create, {:district_effect => valid_attributes}, valid_session
        }.to change(DistrictEffect, :count).by(1)
      end

      it "assigns a newly created district_effect as @district_effect" do
        post :create, {:district_effect => valid_attributes}, valid_session
        expect(assigns(:district_effect)).to be_a(DistrictEffect)
        expect(assigns(:district_effect)).to be_persisted
      end

      it "redirects to the created district_effect" do
        post :create, {:district_effect => valid_attributes}, valid_session
        expect(response).to redirect_to(DistrictEffect.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved district_effect as @district_effect" do
        post :create, {:district_effect => invalid_attributes}, valid_session
        expect(assigns(:district_effect)).to be_a_new(DistrictEffect)
      end

      it "re-renders the 'new' template" do
        post :create, {:district_effect => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested district_effect" do
        district_effect = DistrictEffect.create! valid_attributes
        put :update, {:id => district_effect.to_param, :district_effect => new_attributes}, valid_session
        district_effect.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested district_effect as @district_effect" do
        district_effect = DistrictEffect.create! valid_attributes
        put :update, {:id => district_effect.to_param, :district_effect => valid_attributes}, valid_session
        expect(assigns(:district_effect)).to eq(district_effect)
      end

      it "redirects to the district_effect" do
        district_effect = DistrictEffect.create! valid_attributes
        put :update, {:id => district_effect.to_param, :district_effect => valid_attributes}, valid_session
        expect(response).to redirect_to(district_effect)
      end
    end

    describe "with invalid params" do
      it "assigns the district_effect as @district_effect" do
        district_effect = DistrictEffect.create! valid_attributes
        put :update, {:id => district_effect.to_param, :district_effect => invalid_attributes}, valid_session
        expect(assigns(:district_effect)).to eq(district_effect)
      end

      it "re-renders the 'edit' template" do
        district_effect = DistrictEffect.create! valid_attributes
        put :update, {:id => district_effect.to_param, :district_effect => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested district_effect" do
      district_effect = DistrictEffect.create! valid_attributes
      expect {
        delete :destroy, {:id => district_effect.to_param}, valid_session
      }.to change(DistrictEffect, :count).by(-1)
    end

    it "redirects to the district_effects list" do
      district_effect = DistrictEffect.create! valid_attributes
      delete :destroy, {:id => district_effect.to_param}, valid_session
      expect(response).to redirect_to(district_effects_url)
    end
  end

end
